### ISSUE TITLE
画像の回転について

### ISSUE THREAD

**Issue by ono-hikaru81** [yttmwork/DirectX2DLibraryCpp#1]
画像が回転するとき（DrawTexture の Angle）の中心点についてなのですが、中心点が(0,0)地点になっているのは仕様でしょうか？古いライブラリのほうだと画像の中心がそのまま中心点に設定されていたのですが。

**Comment by yttmwork** [comment]
Engine::SetPivotTypeで描画軸の変更を行って下さい。
例えば`Engine::SetPivotType(PivotType::CenterCenter)`という命令文を書けば描画の位置と拡縮、回転の軸が矩形の中心になります。
「描画の位置と拡縮、回転の軸が矩形の中心になる」とあるように回転だけではなく、座標の位置も変化するので注意してください。

**Comment by ono-hikaru81** [comment]
了解です。ありがとうございます。

2020年9月2日(水) 11:06 yttmwork <notifications@github.com>:
