### ISSUE TITLE
フェードイン・フェードアウトについて

### ISSUE THREAD

**Issue by taishi-matsumura** [yttmwork/DirectX2DLibraryCpp#2]
`Engine.DrawTexture()` を用いてフェードイン・フェードアウトを実現するにはどうすればよいでしょうか。
引数にAlpha値を指定して透明↔不透明を変化させることはできますが、頂点色の指定ができないように思います。

**Comment by yttmwork** [comment]
フェードはDrawRectで矩形に色を設定して行うことを想定していました。
そのため、DrawTexture系に色設定は実装していません。
必要でしたら、本日中に実装して更新します。

**Comment by taishi-matsumura** [comment]
ということは、フェードは
1. 本来描画するテクスチャ等を描画
2. その上からベタ塗りの矩形を `DrawRect()` を用いて描画

とすることで実現すれば良いでしょうか。(黒塗りの矩形の透過率を変化させれば実現可能との認識です)

**Comment by yttmwork** [comment]
> 本来描画するテクスチャ等を描画
その上からベタ塗りの矩形を DrawRect() を用いて描画
とすることで実現すれば良いでしょうか。(黒塗りの矩形の透過率を変化させれば実現可能との認識です)

はい、その方法で実現をお願いします。

**Comment by taishi-matsumura** [comment]
承知しました。
学生にも展開しておきます。
